
title: "First Knit"
author: Areli Nava 
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer 
I attended Eastside High school,and graduated from Eastside High school, English and math share many similar characteristics such as using symbols, words and numbers creating stories and equatic equations,yes I find english to be easier and math more difficult, electives and english were my bests subjects that I did my best in academically, I started to like english in high school and it made me enjoy writing. My electives that I did my best academically was art and ceramics which i enjoyed and even got third place for one of my works of art.
  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
   My personal computer is a Windows my computer knowledge is at about a 5-10 on a scale. sometimes my connection will randomly go away but it has not been a problem just the slow loading.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I prefer to be called by my name "Areli" but if that is difficult to pronounce then whatever is easier 
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   I want to be able to have a very good income enough to not worry about money and have multiple outlooks in lives in different careers, a college subject that would be in my greatest interest would me ceramics and many some business related classes or other forms of art like music
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  
I have been to mexico but only twice,no I have not been to the military and do not plan on joining anytime,if I had to choose a branch it would be air force because it would be very interesting to know how to fly a plane.



## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 
no I have not but currently taking math 115 and no I did not know that information, I want to abtain a B or an A in statistics to  not upset my future plans, my plan is to get into the business world and get some experience and work in other different career very different like fashion or social media and make a name for myself





  




